services:
  mysql:
    image: mysql:8.4
    container_name: mysql-microservicios
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db_usuarios_tienda_urbana
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - microservicios-net
  eureka-server:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    restart: on-failure
    networks:
      - microservicios-net
  usuarios:
    build:
      context: ./usuarios
      dockerfile: Dockerfile
    container_name: ms-usuarios
    ports:
      - "8090:8090"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net
  catalogo:
    build:
      context: ./catalogo
      dockerfile: Dockerfile
    container_name: ms-catalogo
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net
  carrito:
    build:
      context: ./carrito
      dockerfile: Dockerfile
    container_name: ms-carrito
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net
  ordenes:
    build:
      context: ./ordenes
      dockerfile: Dockerfile
    container_name: ms-ordenes
    ports:
      - "8084:8084"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net
  devolucion:
    build:
      context: ./devolucion
      dockerfile: Dockerfile
    container_name: ms-devolucion
    ports:
      - "8086:8086"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net
  envio:
    build:
      context: ./envio
      dockerfile: Dockerfile
    container_name: ms-envio
    ports:
      - "8087:8087"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net
  notificaciones:
    build:
      context: ./notificaciones
      dockerfile: Dockerfile
    container_name: ms-notificaciones
    ports:
      - "8088:8088"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net
  pagos:
    build:
      context: ./pagos
      dockerfile: Dockerfile
    container_name: ms-pagos
    ports:
      - "8089:8089"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net
  resena:
    build:
      context: ./resena
      dockerfile: Dockerfile
    container_name: ms-resena
    ports:
      - "8085:8085"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net
  api-gateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_started
      usuarios:
        condition: service_started
      catalogo:
        condition: service_started
      carrito:
        condition: service_started
      ordenes:
        condition: service_started
      devolucion:
        condition: service_started
      envio:
        condition: service_started
      notificaciones:
        condition: service_started
      pagos:
        condition: service_started
      resena:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net


volumes:
  mysql-data:

networks:
  microservicios-net:
    driver: bridge