server:
  port: 8081

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ruta-ms-usuarios
              uri: lb://usuarios
              predicates:
                - Path=/api/usuarios,/api/usuarios/**
            - id: ruta-ms-catalogo
              uri: lb://catalogo
              predicates:
                - Path=/api/categorias,/api/categorias/**,/api/productos,/api/productos/**
            - id: ruta-ms-carrito
              uri: lb://carrito
              predicates:
                - Path=/api/carrito,/api/carrito/**
            - id: ruta-ms-ordenes
              uri: lb://ordenes
              predicates:
                - Path=/api/ordenes,/api/ordenes/**
            - id: ruta-ms-devolucion
              uri: lb://devolucion
              predicates:
                - Path=/api/devoluciones,/api/devoluciones/**
            - id: ruta-ms-envio
              uri: lb://envio
              predicates:
                - Path=/api/envio,/api/envio/**
            - id: ruta-ms-notificaciones
              uri: lb://notificaciones
              predicates:
                - Path=/api/notificaciones,/api/notificaciones/**
            - id: ruta-ms-pagos
              uri: lb://pagos
              predicates:
                - Path=/api/pagos,/api/pagos/**
            - id: ruta-ms-resena
              uri: lb://resena
              predicates:
                - Path=/api/resenas,/api/resenas**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: apigateway
    instance-id: apigateway:${server.port}

logging:
  level:
    '[org.springframework.cloud.gateway]': DEBUG